export const PREPARE_FINAL_OBJECT = "PREPARE_FINAL_OBJECT";
export const ADD_USER_OBJECT = "ADD_USER_OBJECT";
export const ADD_LOGIN = "ADD_LOGIN";
export const DELETE_ID = "DELETE_ID";

//get response from api
export const FETCH_USERS_STARTED = "FETCH_USERS_STARTED";
export const FETCH_USERS_COMPLETED = "FETCH_USERS_COMPLETED";
export const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";

//get data by id from api
export const FETCH_GETBYID_STARTED = "FETCH_GETBYID_STARTED";
export const FETCH_GETBYID_COMPLETED = "FETCH_GETBYID_COMPLETED";
export const FETCH_GETBYID_FAILED = "FETCH_GETBYID_FAILED";

//update users data
export const UPDATE_USERS_STARTED = "UPDATE_USERS_STARTED";
export const UPDATE_USERS_COMPLETED = "UPDATE_USERS_COMPLETED";
export const UPDATE_USERS_FAILED = "UPDATE_USERS_FAILED";